# Generated by Django 2.0.6 on 2018-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=32)),
                ('upwd', models.CharField(max_length=64)),
                ('utel', models.CharField(max_length=32)),
                ('urole', models.CharField(default='用户', max_length=32)),
                ('upic', models.CharField(max_length=64)),
            ],
        ),
    ]
