# Generated by Django 2.0.6 on 2018-06-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFabulous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField()),
                ('b', models.ForeignKey(on_delete='CASCADE', to='app.Books')),
                ('u', models.ForeignKey(on_delete='CASCADE', to='app.Users')),
            ],
        ),
    ]
