# Generated by Django 2.0.6 on 2018-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addfabulous'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_len', models.IntegerField(default=30)),
                ('b', models.ForeignKey(on_delete='CASCADE', to='app.Books')),
                ('u', models.ForeignKey(on_delete='CASCADE', to='app.Users')),
            ],
        ),
    ]
