# Generated by Django 2.0.6 on 2018-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_borrowbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('ndate_create', models.DateTimeField(auto_now=True)),
                ('ntitle', models.CharField(max_length=64)),
                ('ncontent', models.CharField(max_length=1024)),
                ('nfamily', models.CharField(max_length=32)),
            ],
        ),
    ]
