# Generated by Django 2.0.6 on 2018-06-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfabulous',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Books'),
        ),
        migrations.AlterField(
            model_name='addfabulous',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='borrowbooks',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Books'),
        ),
        migrations.AlterField(
            model_name='borrowbooks',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
    ]
